name: demo vue ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm -v
          npm install
      - name: test
        run: |
          npm run test:unit
      - name: build
        run: |
          npm run build
      - name: deploy
        run: |
          cd dist
          git add --all
          git commit -m "Deploy to gh-pages"
          git push origin gh-pages
        env:
          CI: true
