name: demo vue ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm -v
          npm install
      - name: test
        run: |
          npm run test:unit
      - name: build
        run: |
          npm run build
          cd dist
          ls -lah
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://github.com/chalermporn/demo-vue.git master:gh-pages
        env:
          CI: true
